### ISSUE TITLE
TypeError: Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by vaucci** [mifi/SimpleInstaBot#101]
Hi friends, has anyone been through something similar?

**
![image](https://user-images.githubusercontent.com/57840299/142321294-89ae6b3e-1e82-48a5-8bb3-ace65982ab81.png)
**

**Comment by mifi** [comment]
dup of #36
which version are you running?

**Comment by mifi** [comment]
also could you post the whole log? (copy paste) as well as what you are seeing in the instagram browser window?

**Comment by friendlyG** [comment]
Hi, 
Thank you for making this great tool.
I have just installed it recently on my Win10, version SimpleInstaBot 1.8.3
I see the same error after starting the Bot, I can see it logs into Instagram ok, but after awhile, it start showing codes. Below is the print screen and the log, could you please advise what's the problem, Thank you so much :)

![image](https://user-images.githubusercontent.com/99350173/153246062-61dcc044-8b53-415d-bccb-d2612ee7cfb8.png)

LOGS FROM LAST RUN
12:32 AMSetting language to English (en)
12:32 AMWaiting 2 sec
12:32 AMWaiting 5 sec
12:32 AMFound language selector
12:32 AMSelected language
12:32 AMWaiting 4 sec
12:32 AMWaiting 1 sec
12:32 AMSaving cookies
12:32 AMHave followed/unfollowed 0 in the last hour
12:32 AMHave followed/unfollowed 0 in the last 24 hours
12:32 AMHave liked 0 images in the last 24 hours
12:32 AMUnfollowing currently followed users who were auto-followed more than 5 days ago...
12:32 AMNavigating to user kgtechwear
12:32 AMGoto https://www.instagram.com/kgtechwear
12:32 AMWaiting 2 sec
12:32 AMHas more pages (current 1)
12:32 AMHas more pages (current 2)
12:32 AMHas more pages (current 3)
12:32 AMHas more pages (current 4)
12:32 AMHas more pages (current 5)
12:32 AMHas more pages (current 6)
12:32 AMHas more pages (current 7)
12:32 AMHas more pages (current 8)
12:32 AMHas more pages (current 9)
12:32 AMHas more pages (current 10)
12:32 AMHas more pages (current 11)
12:32 AMError: Navigation failed because browser has disconnected!
12:32 AMSleeping 9.899703572431637 hours (waiting until 10:00)...

**Comment by mifi** [comment]
I created a new issue for you #108
