### ISSUE TITLE
Mixing - following/unfollowing actions

### ISSUE THREAD

**Issue by martiGIT** [mifi/SimpleInstaBot#47]
Hi!
Thanks for resolving previous issues, that's great. I have one more improvement that can may help bot become more efficient. 
By default, bot is starting by unfollowing, as I can see - because of sleeping actions it takes almost half day (literally 5-6h) to finish this job, and than bot starts his following actions. 

This doesn't look to be efficient. Without rebuilding application flow is it possible to mix those actions (for example - unfollow users when bot reaches hourly follow limit? (I know that this may become a problem when `maxFollowsPerHour` is not set-up)

Thanks for you support
Marcin

**Comment by mifi** [comment]
It's possible, but I believe that Instagram doesn't count follows/unfollows separately when it comes to rate limiting.
I don't have any evidence except my personal experience and reading through articles and other bot issues, but I believe it is the case. I remember that once I got Action Blocked, then it doesn't matter if I unfollow or i follow, they will both give me the Action Blocked message. I'm hesitant to change it because it's hard to test and I don't want to risk bans. If you have any evidence that Instagram counts follows/unfollows separately please let me know.

**Comment by martiGIT** [comment]
Thanks for your reasoning. Seems your experience is crucial here. What looks more effective from "human" side may be as you mentioned not so obvious from Instagram automation perspective.
